name: Migrar y validar repositorios GitLab a GitHub

on:
  workflow_dispatch:
    inputs:
      group_gitlab:
        description: "Grupo de GitLab"
        required: false
        type: string

      owner:
        description: "Organización de GitHub"
        required: true
        type: string

jobs:
  migrar:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Instalar jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Dar permisos a los scripts
        run: |
          chmod +x scripts/migrar-repositorios.sh
          chmod +x scripts/validar-integridad-migracion.sh

      - name: Ejecutar migración
        env:
          TOKEN_GITLAB: ${{ secrets.TOKEN_GITLAB }}
          GROUP_GITLAB: ${{ inputs.group_gitlab }}
          TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
          OWNER: ${{ inputs.owner }}
        run: ./scripts/migrar-repositorios.sh

      - name: Ejecutar validación de integridad
        env:
          TOKEN_GITLAB: ${{ secrets.TOKEN_GITLAB }}
          GROUP_GITLAB: ${{ inputs.group_gitlab }}
          TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
          OWNER: ${{ inputs.owner }}
        run: ./scripts/validar-integridad-migracion.sh
